Improve ResultTuple and Add a new Environment module
fewlinesco/kaur pull request #8
Opened 2017-09-08 17:46 UTC by kdisneur

* Add `read` to `Environment` to manage the configuration reading (environment variable)
* Update `ResultTuple`
  * Add `either` which takes two functions and call the good one
  depending of the kind of result tuple
  * Add `error` to create a new `error` tuple from a raw value
  * Add `from_value` to create a new result tuple from a raw value
  `nil` is considered to be an `error`
  * Add `ok` to create a new `ok` tuple from a raw value
* Update documentation to make it fully compatible with `mix docs`

2017-09-09 12:46 UTC, xvw approved these changes

2017-09-09 14:14 UTC, Fenntasy requested changes

2017-09-09 14:14 UTC, Fenntasy commented on lib/kaur/environment.ex
> +  * `{:system, somehing}`: will load the environment variable stored in `somtehing`
☝️  somtehing

2017-09-09 14:14 UTC, Fenntasy commented on lib/kaur/environment.ex
> +  defp deep_get(values, sub_keys) do
you remembered :)

2017-09-11 07:22 UTC, arnaudmorisset approved these changes

2017-09-11 08:01 UTC, Fenntasy approved these changes

2017-09-11 09:29 UTC, merged